server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: billing-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:${MYSQL_PORT:3306}/billing_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    issuer: ${JWT_ISSUER:identity-service}
    secret-base64: ${JWT_SECRET_BASE64:VGhpc0lzTXlTdXBlclNlY3JldEtleUZvckp3dDIwMjQhISE=}

app:
  security:
    public-paths:
      - /health
      - /actuator/health
      - /actuator/info
  services:
    rental: ${RENTAL_SERVICE_URL:http://localhost:8084}
    logistics: ${LOGISTICS_SERVICE_URL:http://localhost:8085}
    maintenance: ${MAINTENANCE_SERVICE_URL:http://localhost:8087}
    customer: ${CUSTOMER_SERVICE_URL:http://localhost:8082}
